fetch_contacts:
  description: "获取通讯录数据, 并保存在.storage/gewe_contacts.json里。本操作为耗时操作,10分钟内重复执行只会更新一次,更新完成后会有通知。"

notify:
  description: "通过Gewe微信发送通知消息"
  fields:
    message:
      description: "要发送的消息内容(仅文本消息有效,其他请随便填)"
      example: "这是测试通知"
    title:
      description: "消息标题(不用填)"
    target:
      description: "接收消息的用户ID或群组ID。只接收一个人作为接收人,接收人的Id可以在.storage/gewe_contacts.json里找。"
      example: "wxid_xxxxxxxx"
